### ISSUE TITLE
Constant not taken into account correctly whe using value_and_covariance

### ISSUE THREAD

**Issue by acampove** [HDembinski/essays#8]
Hi,

I see that:

```python
a = (17.34674, 0.0398)
b = (17.33603, 0.0412)

val=value_and_covariance("2 * (a - b) / (a + b)", a=a, b=b)
print( 100 * val[0], 100 * val[1])

val=value_and_covariance("100 * 2 * (a - b) / (a + b)", a=a, b=b)
print(val[0], val[1])
```
gives me different results:

```
0.06175977293624213 0.026935319768254033
0.06175977293623967 2.693531976825403
```
From what I understant the 100 should just scale the error so both results should agree. 

Cheers.

**Comment by HDembinski** [comment]
The function returns the value and the variance of the value. If you scale the value by 100, the variance gets scaled by 100^2. If you take that into account, you will see that the function returns the right answer.

**Comment by acampove** [comment]
I do not get this. You are using:

![image](https://user-images.githubusercontent.com/14037062/150739234-c8ee308c-d169-43d1-898d-95075140d65c.png)

right? If you do `f -> 100 f` then the error should be scaled by `100`. I mean, you are taking the 100 out of the squared parentheses and then out of the square root.

**Comment by acampove** [comment]
Oh, wait, you said variance. Then this makes sense, I would remove the square root from the formula above. However no one really uses the variance. Anyone looking for this type of function would want something that returns the value and error. So it's kind of an odd choice to make the function return the square of the error alongside the value.

**Comment by HDembinski** [comment]
Variances are fundamental properties in statistics, not standard deviations. Variances are additive like normal numbers, while standard deviations need to be added in quadrature. It is silly and inefficient to make an API return the error, when you actually need the variance. Because then the API always takes the square root which you have to undo. It is a subtlety you can only appreciate when you think about it for a long time.
